In [1]:
import torch 
import torchvision
import functools
import numpy as np
from torch import nn

from brainscore import score_model
from brainscore.benchmarks import public_benchmark_pool
from model_tools.activations.pytorch import PytorchWrapper
from model_tools.activations.pytorch import load_preprocess_images
from model_tools.brain_transformation import ModelCommitment
from model_tools.check_submission import check_models

model = torchvision.models.alexnet(pretrained=True).to("cpu")
preprocessing = functools.partial(load_preprocess_images, image_size=224)
activations_model = PytorchWrapper(identifier='alexnet', model=model, preprocessing=preprocessing)
activations_model.image_size = 224


/home/ubuntu/anaconda3/envs/pytorch/lib/python3.8/site-packages/brainscore/metrics/__init__.py:37: FutureWarning: xarray subclass Score should explicitly define __slots__
  class Score(DataAssembly):


In [2]:
model

AlexNet(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(11, 11), stride=(4, 4), padding=(2, 2))
    (1): ReLU(inplace=True)
    (2): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (3): Conv2d(64, 192, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2))
    (4): ReLU(inplace=True)
    (5): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
    (6): Conv2d(192, 384, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (7): ReLU(inplace=True)
    (8): Conv2d(384, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (9): ReLU(inplace=True)
    (10): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): MaxPool2d(kernel_size=3, stride=2, padding=0, dilation=1, ceil_mode=False)
  )
  (avgpool): AdaptiveAvgPool2d(output_size=(6, 6))
  (classifier): Sequential(
    (0): Dropout(p=0.5, inplace=False)
    (1): Linear(in_features=9216, out_features=4096, bias=True)
 

In [3]:
commited_model = ModelCommitment(identifier='alexnet', activations_model=activations_model,
                                 layers=['features.2', 'features.12'])

score = score_model(model_identifier='alexnet', model=commited_model,
                    benchmark_identifier='movshon.FreemanZiemba2013public.V1-pls')

print(score)

cross-validation: 100%|██████████| 10/10 [12:53<00:00, 77.37s/it]

<xarray.Score (aggregation: 2)>
array([0.29724036, 0.00816442])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.48018942...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.88076227...
    model_identifier:      alexnet
    benchmark_identifier:  movshon.FreemanZiemba2013public.V1-pls


In [4]:
score = score_model(model_identifier='alexnet', model=commited_model,
                    benchmark_identifier='movshon.FreemanZiemba2013public.V2-pls')

print(score)

Loading lookup from entrypoints
Loading lookup from /home/ubuntu/anaconda3/envs/pytorch/lib/python3.8/site-packages/brainscore/lookup.csv


cross-validation: 100%|██████████| 10/10 [05:40<00:00, 34.09s/it]

cross-validation: 100%|██████████| 10/10 [06:32<00:00, 39.29s/it]

<xarray.Score (aggregation: 2)>
array([0.3073184 , 0.01641874])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.4539591 ...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.8188841 ...
    model_identifier:      alexnet
    benchmark_identifier:  movshon.FreemanZiemba2013public.V2-pls


In [5]:
score = score_model(model_identifier='alexnet', model=commited_model,
                    benchmark_identifier='dicarlo.MajajHong2015public.V4-pls')

print(score)

activations: 100%|██████████| 3200/3200 [02:24<00:00, 22.08it/s]

layer packaging: 100%|██████████| 2/2 [00:00<00:00, 86.01it/s]

cross-validation: 100%|██████████| 10/10 [06:03<00:00, 36.38s/it]

cross-validation: 100%|██████████| 10/10 [23:58<00:00, 143.82s/it]

<xarray.Score (aggregation: 2)>
array([0.48276818, 0.00676272])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.61406253...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.88377819...
    model_identifier:      alexnet
    benchmark_identifier:  dicarlo.MajajHong2015public.V4-pls


In [6]:
score = score_model(model_identifier='alexnet', model=commited_model,
                    benchmark_identifier='dicarlo.MajajHong2015public.IT-pls')

print(score)

cross-validation: 100%|██████████| 10/10 [22:55<00:00, 137.51s/it]


<xarray.Score (aggregation: 2)>
array([0.50478953, 0.00269298])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.57961356...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.81579938...
    model_identifier:      alexnet
    benchmark_identifier:  dicarlo.MajajHong2015public.IT-pls
