In [1]:
import torch 
import torchvision
import functools
import numpy as np
from torch import nn

from brainscore import score_model
from brainscore.benchmarks import public_benchmark_pool
from model_tools.activations.pytorch import PytorchWrapper
from model_tools.activations.pytorch import load_preprocess_images
from model_tools.brain_transformation import ModelCommitment
from model_tools.check_submission import check_models

model = torchvision.models.resnet18(pretrained=True).to('cpu')
preprocessing = functools.partial(load_preprocess_images, image_size=224)
activations_model = PytorchWrapper(identifier='resnet50', model=model, preprocessing=preprocessing)
activations_model.image_size = 224


/home/ubuntu/anaconda3/envs/pytorch/lib/python3.8/site-packages/brainscore/metrics/__init__.py:37: FutureWarning: xarray subclass Score should explicitly define __slots__
  class Score(DataAssembly):


In [2]:
model

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  

In [3]:
commited_model = ModelCommitment(identifier='resnet50', activations_model=activations_model,
                                 layers=['layer1.1.bn2', 'layer4.1.bn2'])

score = score_model(model_identifier='resnet50', model=commited_model,
                    benchmark_identifier='movshon.FreemanZiemba2013public.V1-pls')

print(score)

cross-validation:  20%|██        | 2/10 [03:25<13:30, 101.36s/it]/home/ubuntu/anaconda3/envs/pytorch/lib/python3.8/site-packages/sklearn/cross_decomposition/_pls.py:96: ConvergenceWarning: Maximum number of iterations reached
  warnings.warn('Maximum number of iterations reached',
cross-validation: 100%|██████████| 10/10 [16:47<00:00, 100.70s/it]

<xarray.Score (aggregation: 2)>
array([0.14121484, 0.0155345 ])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.33097781...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.88076227...
    model_identifier:      resnet50
    benchmark_identifier:  movshon.FreemanZiemba2013public.V1-pls


In [4]:
score = score_model(model_identifier='resnet50', model=commited_model,
                    benchmark_identifier='movshon.FreemanZiemba2013public.V2-pls')

print(score)

cross-validation: 100%|██████████| 10/10 [08:08<00:00, 48.88s/it]

<xarray.Score (aggregation: 2)>
array([0.24573152, 0.01064551])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.40593161...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.8188841 ...
    model_identifier:      resnet50
    benchmark_identifier:  movshon.FreemanZiemba2013public.V2-pls


In [5]:
score = score_model(model_identifier='resnet50', model=commited_model,
                    benchmark_identifier='dicarlo.MajajHong2015public.V4-pls')

print(score)

Loading lookup from entrypoints
Loading lookup from /home/ubuntu/anaconda3/envs/pytorch/lib/python3.8/site-packages/brainscore/lookup.csv


activations: 100%|██████████| 3200/3200 [02:35<00:00, 20.57it/s]

layer packaging: 100%|██████████| 2/2 [00:00<00:00, 87.41it/s]

cross-validation: 100%|██████████| 10/10 [1:05:51<00:00, 395.10s/it]


<xarray.Score (aggregation: 2)>
array([0.48851486, 0.00500676])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.6177065 ...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.88377819...
    model_identifier:      resnet50
    benchmark_identifier:  dicarlo.MajajHong2015public.V4-pls


In [6]:
score = score_model(model_identifier='resnet50', model=commited_model,
                    benchmark_identifier='dicarlo.MajajHong2015public.IT-pls')

print(score)

cross-validation: 100%|██████████| 10/10 [15:13<00:00, 91.33s/it]

<xarray.Score (aggregation: 2)>
array([0.47789128, 0.00375194])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.56395951...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.81579938...
    model_identifier:      resnet50
    benchmark_identifier:  dicarlo.MajajHong2015public.IT-pls
