In [1]:
import torch 
import torchvision
import functools
import numpy as np
from torch import nn

from brainscore import score_model
from brainscore.benchmarks import public_benchmark_pool
from model_tools.activations.pytorch import PytorchWrapper
from model_tools.activations.pytorch import load_preprocess_images
from model_tools.brain_transformation import ModelCommitment
from model_tools.check_submission import check_models

model = torchvision.models.vgg16(pretrained=True).to("cpu")
preprocessing = functools.partial(load_preprocess_images, image_size=224)
activations_model = PytorchWrapper(identifier='vgg16', model=model, preprocessing=preprocessing)
activations_model.image_size = 224


/home/ubuntu/anaconda3/envs/pytorch/lib/python3.8/site-packages/brainscore/metrics/__init__.py:37: FutureWarning: xarray subclass Score should explicitly define __slots__
  class Score(DataAssembly):


In [2]:
model

VGG(
  (features): Sequential(
    (0): Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (1): ReLU(inplace=True)
    (2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (3): ReLU(inplace=True)
    (4): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (5): Conv2d(64, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (6): ReLU(inplace=True)
    (7): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (8): ReLU(inplace=True)
    (9): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False)
    (10): Conv2d(128, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (11): ReLU(inplace=True)
    (12): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (13): ReLU(inplace=True)
    (14): Conv2d(256, 256, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (15): ReLU(inplace=True)
    (16): MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1

In [3]:
commited_model = ModelCommitment(identifier='vgg16', activations_model=activations_model,
                                 layers=['features.4', 'features.30'])

score = score_model(model_identifier='vgg16', model=commited_model,
                    benchmark_identifier='movshon.FreemanZiemba2013public.V1-pls')

print(score)

cross-validation: 100%|██████████| 10/10 [24:37<00:00, 147.75s/it]

<xarray.Score (aggregation: 2)>
array([0.1545702 , 0.01466148])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.34627535...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.88076227...
    model_identifier:      vgg16
    benchmark_identifier:  movshon.FreemanZiemba2013public.V1-pls


In [4]:
score = score_model(model_identifier='vgg16', model=commited_model,
                    benchmark_identifier='movshon.FreemanZiemba2013public.V2-pls')

print(score)

cross-validation: 100%|██████████| 10/10 [11:06<00:00, 66.62s/it]

<xarray.Score (aggregation: 2)>
array([0.26004136, 0.0099232 ])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.41758381...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.8188841 ...
    model_identifier:      vgg16
    benchmark_identifier:  movshon.FreemanZiemba2013public.V2-pls


In [5]:
score = score_model(model_identifier='vgg16', model=commited_model,
                    benchmark_identifier='dicarlo.MajajHong2015public.V4-pls')

print(score)

Loading lookup from entrypoints
Loading lookup from /home/ubuntu/anaconda3/envs/pytorch/lib/python3.8/site-packages/brainscore/lookup.csv


activations: 100%|██████████| 3200/3200 [03:55<00:00, 13.58it/s]

layer packaging: 100%|██████████| 2/2 [00:00<00:00, 71.40it/s]

cross-validation: 100%|██████████| 10/10 [3:02:44<00:00, 1096.48s/it] 


<xarray.Score (aggregation: 2)>
array([0.49132404, 0.00542675])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.61947999...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.88377819...
    model_identifier:      vgg16
    benchmark_identifier:  dicarlo.MajajHong2015public.V4-pls


In [6]:
score = score_model(model_identifier='vgg16', model=commited_model,
                    benchmark_identifier='dicarlo.MajajHong2015public.IT-pls')

print(score)

cross-validation: 100%|██████████| 10/10 [06:03<00:00, 36.32s/it]

<xarray.Score (aggregation: 2)>
array([0.51850755, 0.00328962])
Coordinates:
  * aggregation  (aggregation) <U6 'center' 'error'
Attributes:
    raw:                   <xarray.Score (aggregation: 2)>\narray([0.58743648...
    ceiling:               <xarray.Score (aggregation: 2)>\narray([0.81579938...
    model_identifier:      vgg16
    benchmark_identifier:  dicarlo.MajajHong2015public.IT-pls
